# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LanguageTranslationAR' do
  use_frameworks!
  pod 'PopupDialog', '~> 0.7'


  # Pods for LanguageTranslationAR

end
